module Koffein.ItemLists exposing (..)

data =
  [
    [
      ( 1, "weiß", "green" )
    , ( 2, "gelb", "magenta" )
    , ( 3, "grün", "gold" )
    , ( 4, "grün", "darkorange" )
    , ( 5, "rot", "darkorange" )
    , ( 6, "blau", "darkorange" )
    , ( 7, "blau", "magenta" )
    , ( 8, "gelb", "red" )
    , ( 9, "lila", "darkorange" )
    , ( 10, "grün", "gold" )
    , ( 11, "rot", "green" )
    , ( 12, "lila", "magenta" )
    , ( 13, "weiß", "black" )
    , ( 14, "gelb", "darkorange" )
    , ( 15, "rot", "red" )
    , ( 16, "weiß", "gold" )
    , ( 17, "grün", "gold" )
    , ( 18, "gelb", "black" )
    , ( 19, "rot", "red" )
    , ( 20, "weiß", "green" )
    , ( 21, "blau", "green" )
    , ( 22, "blau", "black" )
    , ( 23, "schwarz", "red" )
    , ( 24, "schwarz", "green" )
    , ( 25, "schwarz", "black" )
    ]
  , [
      ( 1, "lila", "green" )
    , ( 2, "rot", "red" )
    , ( 3, "weiß", "darkorange" )
    , ( 4, "gelb", "gold" )
    , ( 5, "weiß", "gold" )
    , ( 6, "gelb", "black" )
    , ( 7, "gelb", "gold" )
    , ( 8, "schwarz", "magenta" )
    , ( 9, "schwarz", "black" )
    , ( 10, "rot", "black" )
    , ( 11, "grün", "gold" )
    , ( 12, "lila", "green" )
    , ( 13, "gelb", "magenta" )
    , ( 14, "blau", "gold" )
    , ( 15, "schwarz", "green" )
    , ( 16, "weiß", "gold" )
    , ( 17, "lila", "magenta" )
    , ( 18, "rot", "gold" )
    , ( 19, "schwarz", "darkorange" )
    , ( 20, "grün", "red" )
    , ( 21, "blau", "magenta" )
    , ( 22, "schwarz", "red" )
    , ( 23, "rot", "red" )
    , ( 24, "weiß", "black" )
    , ( 25, "schwarz", "gold" )
    ]
  , [
      ( 1, "schwarz", "gold" )
    , ( 2, "gelb", "darkorange" )
    , ( 3, "rot", "darkorange" )
    , ( 4, "lila", "black" )
    , ( 5, "rot", "darkorange" )
    , ( 6, "grün", "green" )
    , ( 7, "rot", "gold" )
    , ( 8, "rot", "red" )
    , ( 9, "lila", "black" )
    , ( 10, "rot", "darkorange" )
    , ( 11, "schwarz", "magenta" )
    , ( 12, "rot", "gold" )
    , ( 13, "weiß", "black" )
    , ( 14, "schwarz", "magenta" )
    , ( 15, "rot", "darkorange" )
    , ( 16, "weiß", "magenta" )
    , ( 17, "weiß", "black" )
    , ( 18, "lila", "gold" )
    , ( 19, "blau", "green" )
    , ( 20, "rot", "red" )
    , ( 21, "schwarz", "darkorange" )
    , ( 22, "gelb", "red" )
    , ( 23, "lila", "darkorange" )
    , ( 24, "rot", "gold" )
    , ( 25, "weiß", "gold" )
    ]
  , [
      ( 1, "schwarz", "magenta" )
    , ( 2, "weiß", "magenta" )
    , ( 3, "weiß", "gold" )
    , ( 4, "blau", "black" )
    , ( 5, "grün", "gold" )
    , ( 6, "lila", "red" )
    , ( 7, "schwarz", "black" )
    , ( 8, "weiß", "green" )
    , ( 9, "lila", "green" )
    , ( 10, "weiß", "black" )
    , ( 11, "schwarz", "gold" )
    , ( 12, "schwarz", "green" )
    , ( 13, "rot", "green" )
    , ( 14, "weiß", "red" )
    , ( 15, "gelb", "green" )
    , ( 16, "lila", "darkorange" )
    , ( 17, "weiß", "green" )
    , ( 18, "grün", "black" )
    , ( 19, "lila", "red" )
    , ( 20, "gelb", "green" )
    , ( 21, "blau", "black" )
    , ( 22, "schwarz", "magenta" )
    , ( 23, "weiß", "magenta" )
    , ( 24, "gelb", "gold" )
    , ( 25, "gelb", "green" )
    ]
  , [
      ( 1, "gelb", "gold" )
    , ( 2, "grün", "darkorange" )
    , ( 3, "weiß", "magenta" )
    , ( 4, "gelb", "magenta" )
    , ( 5, "blau", "black" )
    , ( 6, "grün", "red" )
    , ( 7, "blau", "green" )
    , ( 8, "grün", "red" )
    , ( 9, "lila", "black" )
    , ( 10, "lila", "gold" )
    , ( 11, "schwarz", "black" )
    , ( 12, "weiß", "gold" )
    , ( 13, "lila", "magenta" )
    , ( 14, "rot", "darkorange" )
    , ( 15, "grün", "red" )
    , ( 16, "lila", "gold" )
    , ( 17, "schwarz", "darkorange" )
    , ( 18, "blau", "gold" )
    , ( 19, "gelb", "red" )
    , ( 20, "lila", "red" )
    , ( 21, "schwarz", "magenta" )
    , ( 22, "lila", "magenta" )
    , ( 23, "blau", "gold" )
    , ( 24, "blau", "darkorange" )
    , ( 25, "lila", "green" )
    ]
  , [
      ( 1, "rot", "red" )
    , ( 2, "rot", "gold" )
    , ( 3, "blau", "black" )
    , ( 4, "schwarz", "darkorange" )
    , ( 5, "weiß", "gold" )
    , ( 6, "grün", "black" )
    , ( 7, "lila", "gold" )
    , ( 8, "gelb", "gold" )
    , ( 9, "gelb", "magenta" )
    , ( 10, "blau", "red" )
    , ( 11, "gelb", "black" )
    , ( 12, "blau", "gold" )
    , ( 13, "rot", "green" )
    , ( 14, "grün", "gold" )
    , ( 15, "weiß", "red" )
    , ( 16, "blau", "green" )
    , ( 17, "blau", "gold" )
    , ( 18, "grün", "red" )
    , ( 19, "schwarz", "black" )
    , ( 20, "lila", "black" )
    , ( 21, "schwarz", "gold" )
    , ( 22, "gelb", "gold" )
    , ( 23, "gelb", "darkorange" )
    , ( 24, "lila", "green" )
    , ( 25, "gelb", "black" )
    ]
  , [
      ( 1, "gelb", "darkorange" )
    , ( 2, "rot", "green" )
    , ( 3, "gelb", "magenta" )
    , ( 4, "blau", "magenta" )
    , ( 5, "lila", "darkorange" )
    , ( 6, "rot", "black" )
    , ( 7, "blau", "black" )
    , ( 8, "blau", "gold" )
    , ( 9, "schwarz", "black" )
    , ( 10, "blau", "gold" )
    , ( 11, "rot", "gold" )
    , ( 12, "blau", "gold" )
    , ( 13, "blau", "green" )
    , ( 14, "grün", "red" )
    , ( 15, "blau", "black" )
    , ( 16, "gelb", "darkorange" )
    , ( 17, "weiß", "black" )
    , ( 18, "gelb", "red" )
    , ( 19, "weiß", "red" )
    , ( 20, "rot", "darkorange" )
    , ( 21, "grün", "black" )
    , ( 22, "weiß", "red" )
    , ( 23, "blau", "black" )
    , ( 24, "rot", "magenta" )
    , ( 25, "lila", "magenta" )
    ]
  , [
      ( 1, "grün", "gold" )
    , ( 2, "grün", "black" )
    , ( 3, "lila", "magenta" )
    , ( 4, "lila", "darkorange" )
    , ( 5, "weiß", "red" )
    , ( 6, "rot", "black" )
    , ( 7, "gelb", "red" )
    , ( 8, "grün", "black" )
    , ( 9, "grün", "magenta" )
    , ( 10, "blau", "gold" )
    , ( 11, "blau", "red" )
    , ( 12, "lila", "darkorange" )
    , ( 13, "lila", "red" )
    , ( 14, "blau", "gold" )
    , ( 15, "gelb", "darkorange" )
    , ( 16, "rot", "green" )
    , ( 17, "rot", "red" )
    , ( 18, "schwarz", "darkorange" )
    , ( 19, "schwarz", "black" )
    , ( 20, "schwarz", "red" )
    , ( 21, "weiß", "green" )
    , ( 22, "weiß", "red" )
    , ( 23, "blau", "black" )
    , ( 24, "gelb", "darkorange" )
    , ( 25, "lila", "darkorange" )
    ]
  , [
      ( 1, "weiß", "darkorange" )
    , ( 2, "gelb", "red" )
    , ( 3, "gelb", "red" )
    , ( 4, "weiß", "black" )
    , ( 5, "weiß", "red" )
    , ( 6, "lila", "black" )
    , ( 7, "schwarz", "magenta" )
    , ( 8, "weiß", "magenta" )
    , ( 9, "grün", "black" )
    , ( 10, "rot", "magenta" )
    , ( 11, "weiß", "darkorange" )
    , ( 12, "blau", "red" )
    , ( 13, "gelb", "red" )
    , ( 14, "blau", "red" )
    , ( 15, "grün", "red" )
    , ( 16, "grün", "darkorange" )
    , ( 17, "lila", "magenta" )
    , ( 18, "schwarz", "red" )
    , ( 19, "blau", "green" )
    , ( 20, "rot", "darkorange" )
    , ( 21, "gelb", "red" )
    , ( 22, "rot", "red" )
    , ( 23, "blau", "red" )
    , ( 24, "blau", "gold" )
    , ( 25, "gelb", "red" )
    ]
  , [
      ( 1, "blau", "darkorange" )
    , ( 2, "grün", "gold" )
    , ( 3, "lila", "magenta" )
    , ( 4, "rot", "red" )
    , ( 5, "weiß", "red" )
    , ( 6, "rot", "black" )
    , ( 7, "blau", "green" )
    , ( 8, "weiß", "red" )
    , ( 9, "blau", "black" )
    , ( 10, "blau", "gold" )
    , ( 11, "weiß", "green" )
    , ( 12, "rot", "black" )
    , ( 13, "schwarz", "darkorange" )
    , ( 14, "rot", "green" )
    , ( 15, "gelb", "gold" )
    , ( 16, "rot", "gold" )
    , ( 17, "blau", "black" )
    , ( 18, "schwarz", "darkorange" )
    , ( 19, "blau", "black" )
    , ( 20, "blau", "gold" )
    , ( 21, "rot", "gold" )
    , ( 22, "schwarz", "darkorange" )
    , ( 23, "lila", "black" )
    , ( 24, "schwarz", "magenta" )
    , ( 25, "blau", "magenta" )
    ]
  ]
