module ItemLists exposing (..)

data =
  [
    [
      ( 1, "rot", "red" )
    , ( 2, "rot", "magenta" )
    , ( 3, "blau", "red" )
    , ( 4, "lila", "green" )
    , ( 5, "gelb", "green" )
    , ( 6, "weiß", "green" )
    , ( 7, "gelb", "red" )
    , ( 8, "weiß", "magenta" )
    , ( 9, "weiß", "darkorange" )
    , ( 10, "lila", "red" )
    , ( 11, "weiß", "magenta" )
    , ( 12, "grün", "darkorange" )
    , ( 13, "weiß", "green" )
    , ( 14, "grün", "magenta" )
    , ( 15, "blau", "red" )
    , ( 16, "lila", "gold" )
    , ( 17, "lila", "gold" )
    , ( 18, "schwarz", "magenta" )
    , ( 19, "gelb", "magenta" )
    , ( 20, "grün", "green" )
    ]
  , [
      ( 1, "blau", "gold" )
    , ( 2, "gelb", "darkorange" )
    , ( 3, "lila", "darkorange" )
    , ( 4, "schwarz", "black" )
    , ( 5, "weiß", "green" )
    , ( 6, "lila", "green" )
    , ( 7, "schwarz", "green" )
    , ( 8, "rot", "green" )
    , ( 9, "weiß", "green" )
    , ( 10, "lila", "gold" )
    , ( 11, "lila", "red" )
    , ( 12, "gelb", "black" )
    , ( 13, "grün", "darkorange" )
    , ( 14, "gelb", "black" )
    , ( 15, "lila", "magenta" )
    , ( 16, "gelb", "red" )
    , ( 17, "rot", "darkorange" )
    , ( 18, "schwarz", "red" )
    , ( 19, "blau", "black" )
    , ( 20, "lila", "magenta" )
    ]
  , [
      ( 1, "schwarz", "black" )
    , ( 2, "grün", "green" )
    , ( 3, "weiß", "gold" )
    , ( 4, "schwarz", "darkorange" )
    , ( 5, "schwarz", "magenta" )
    , ( 6, "gelb", "black" )
    , ( 7, "gelb", "red" )
    , ( 8, "schwarz", "red" )
    , ( 9, "rot", "red" )
    , ( 10, "weiß", "magenta" )
    , ( 11, "grün", "black" )
    , ( 12, "weiß", "black" )
    , ( 13, "weiß", "black" )
    , ( 14, "schwarz", "red" )
    , ( 15, "weiß", "green" )
    , ( 16, "schwarz", "darkorange" )
    , ( 17, "grün", "black" )
    , ( 18, "gelb", "red" )
    , ( 19, "rot", "gold" )
    , ( 20, "blau", "darkorange" )
    ]
  , [
      ( 1, "grün", "darkorange" )
    , ( 2, "lila", "darkorange" )
    , ( 3, "gelb", "gold" )
    , ( 4, "schwarz", "darkorange" )
    , ( 5, "grün", "green" )
    , ( 6, "grün", "magenta" )
    , ( 7, "blau", "darkorange" )
    , ( 8, "lila", "black" )
    , ( 9, "schwarz", "darkorange" )
    , ( 10, "gelb", "magenta" )
    , ( 11, "gelb", "magenta" )
    , ( 12, "grün", "magenta" )
    , ( 13, "lila", "green" )
    , ( 14, "grün", "black" )
    , ( 15, "blau", "green" )
    , ( 16, "rot", "red" )
    , ( 17, "rot", "red" )
    , ( 18, "rot", "darkorange" )
    , ( 19, "lila", "black" )
    , ( 20, "weiß", "black" )
    ]
  , [
      ( 1, "rot", "gold" )
    , ( 2, "rot", "green" )
    , ( 3, "gelb", "green" )
    , ( 4, "gelb", "black" )
    , ( 5, "gelb", "red" )
    , ( 6, "blau", "gold" )
    , ( 7, "weiß", "black" )
    , ( 8, "weiß", "magenta" )
    , ( 9, "blau", "magenta" )
    , ( 10, "lila", "darkorange" )
    , ( 11, "lila", "black" )
    , ( 12, "lila", "green" )
    , ( 13, "schwarz", "gold" )
    , ( 14, "grün", "darkorange" )
    , ( 15, "weiß", "magenta" )
    , ( 16, "rot", "green" )
    , ( 17, "schwarz", "red" )
    , ( 18, "rot", "magenta" )
    , ( 19, "weiß", "gold" )
    , ( 20, "blau", "green" )
    ]
  ]
